export enum Amenities {
	PROJECTOR = 'Projector',
	WHITEBOARD = 'Whiteboard',
	VIDEO_CONFERENCING = 'Video Conferencing',
	WIFI = 'Wifi',
	FOURK_DISPLAY = '4K Display',
	SURROUND_SOUND = 'Surround Sound',
	CLIMATE_CONTROL = 'Climate Control',
	MICROPHONE = 'Microphone',
	RECORDING_EQUIPMENT = 'Record Equipment',
	COFFEE_STATION = 'Coffee Station',
	NOISE_CANCELLATION = 'Noise Cancellation',
	DUAL_PROJECTORS = 'Dual Projectors',
	STANDING_DESKS = 'Standing Desks',
	STAGE = 'Stage',
	WRITABLE_WALLS = 'Writable Walls',
	PA_SYSTEM = "PA System",
	CATERING_STATION = 'Capacity Station',
	LOUNGE_SEATING = 'Lounge Seating',
	MINI_FRIDGE = 'Mini Fridge',
}
