spring:
  application:
    name: gvoRBA Backend

  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: booking
    password: booking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
