CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE rooms_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE bookings_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE refresh_token_seq START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE roles_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE roles
(
	role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	role_name VARCHAR(255)                            NOT NULL,
	CONSTRAINT pk_roles PRIMARY KEY (role_id)
);

CREATE TABLE users
(
	id         BIGINT PRIMARY KEY,
	email      VARCHAR(255),
	password   VARCHAR(255),
	name       VARCHAR(255),
	role       BIGINT NOT NULL REFERENCES roles (role_id),
	created_on TIMESTAMP
);
CREATE TABLE rooms
(
	id         BIGINT PRIMARY KEY,
	name       VARCHAR(255) NOT NULL,
	location   VARCHAR(255),
	capacity   INTEGER,
	amenities  TEXT[],
	is_active  BOOLEAN,
	created_on TIMESTAMP
);

CREATE TABLE bookings
(
	id        BIGINT PRIMARY KEY,
	room_id   BIGINT NOT NULL REFERENCES rooms (id),
	starts_at TIMESTAMP,
	ends_at   TIMESTAMP,
	purpose   VARCHAR(255),
	status    SMALLINT
);

CREATE TABLE refresh_token
(
	id  BIGINT PRIMARY KEY,
	user_id BIGINT REFERENCES users (id),
	token_hash VARCHAR(255) NOT NULL UNIQUE,
	expires_at TIMESTAMP NOT NULL,
	revoked_at TIMESTAMP
);

