cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}

spring:
  application:
    name: gvoRBA Backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/booking}
    username: ${DB_USERNAME:booking}
    password: ${DB_PASSWORD:booking}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
